version: '3.1'

services:
  testra:
    image: testra/testra-api:1.0-SNAPSHOT
    container_name: testra-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: vepo/mongo
    container_name: testra-monogo
    restart: always
    volumes:
      - $HOME/data/testra-mongo-data:/data/db
      - $HOME/data/testra-mongo-bkp:/data/bkp
    ports:
      - 27017:27017
    environment:
      - AUTH=yes
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - APPLICATION_DATABASE=testra
      - APPLICATION_USER=testra
      - APPLICATION_PASS=password
